FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

ARG NEXT_PUBLIC_AUTH_API_URL=/api/auth
ARG NEXT_PUBLIC_FLOWISE_PROXY_URL=http://flowise-proxy:4000

ENV NEXT_PUBLIC_AUTH_API_URL=${NEXT_PUBLIC_AUTH_API_URL}
ENV NEXT_PUBLIC_FLOWISE_PROXY_URL=${NEXT_PUBLIC_FLOWISE_PROXY_URL}
ENV NODE_ENV=production

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
