{
 "title": "RizzyBytes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Avg %",
   "type": "timeseries",
   "description": "CPU Usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Avg %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(nvidia_smi_utilization_gpu_ratio * on (uuid) group_left(name) nvidia_smi_gpu_info)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VRAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(nvidia_smi_memory_used_bytes / nvidia_smi_memory_total_bytes * 100)\r\n  * on (uuid) group_left(name) nvidia_smi_gpu_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used memory"
    },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached memory" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffer memory" }
   ]
  },
  {
   "title": "Chatbot Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, route)(\r\n    rate(flowise_proxy_http_request_duration_seconds_bucket{route=~\"/api/v1/prediction/:flowId\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Chatbot Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (route, method, status_code)(\r\n  rate(flowise_proxy_http_request_duration_seconds_count{route=~\"/api/v1/prediction/.+\"}[1m])\r\n)\r\n",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Flowise-proxy HTTP latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(flowise_proxy_http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95 flowise-proxy"
    }
   ]
  },
  {
   "title": "Listener job rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (queue,type,status)(rate(listener_jobs_total[5m]))",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "VRAM Used Vs. VRAM Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes * on (uuid) group_left(name) nvidia_smi_gpu_info",
     "legendFormat": "{{name}} VRAM Used"
    },
    {
     "expr": "nvidia_smi_memory_total_bytes * on (uuid) group_left(name) nvidia_smi_gpu_info",
     "legendFormat": "{{name}} VRAM Total"
    }
   ]
  },
  {
   "title": "Broker publish rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (routing_key)(rate(broker_rabbit_published_total[5m]))",
     "legendFormat": "{{routing_key}}"
    }
   ]
  },
  {
   "title": "Mail send rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (status)(rate(mail_emails_sent_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Logger ingest rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(logger_logs_ingested_total[5m])",
     "legendFormat": "logs"
    }
   ]
  }
 ]
}